/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation';

export const defaultNavigation: FuseNavigationItem[] = [
    {
        id      : 'inmobiliaria',
        title   : 'Inmobiliaria aaaaa',
        subtitle: 'Modulo de Inmobiliari aa',
        type    : 'group',
        icon    : 'heroicons_outline:home',
        children: [
            {
                id   : 'inmobiliaria.incorporacion',
                title: 'Incorporacion',
                type : 'basic',
                icon : 'heroicons_outline:arrow-down-on-square-stack',
                link : '/inmobiliaria/incorporacion',
            },
            {
                id   : 'inmobiliaria.ingresos',
                title: 'Ingresos',
                type : 'basic',
                icon : 'heroicons_outline:academic-cap',
                link : '/inmobiliaria/ingresos',
            },
            {
                id   : 'inmobiliaria.margesi',
                title: 'Margesi',
                type : 'basic',
                icon : 'heroicons_outline:building-office-2',
                link : '/inmobiliaria/margesi',
            },
            {
                id   : 'inmobiliaria.contacts',
                title: 'Margesi Mapa',
                type : 'basic',
                icon : 'heroicons_outline:map',
                link : '/inmobiliaria/contacts',
            },            
            {
                id   : 'inmobiliaria.file-manager',
                title: 'Autoriza anulacion rentas',
                type : 'basic',
                icon : 'heroicons_outline:shield-check',
                link : '/inmobiliaria/file-manager',
            },
            {
                id      : 'inmobiliaria.help-center',
                title   : 'PIDE',
                type    : 'collapsable',
                icon    : 'heroicons_outline:identification',
                link    : '/inmobiliaria/help-center',
                children: [
                    {
                        id        : 'inmobiliaria.help-center.home',
                        title     : 'Consultas PIDE',
                        type      : 'basic',
                        icon      : 'heroicons_outline:finger-print',
                        link      : '/inmobiliaria/help-center',
                    },
                ],
            },
            {
                id      : 'inmobiliaria.subasta',
                title   : 'Subasta',
                type    : 'collapsable',
                icon    : 'heroicons_outline:bookmark-square',
                link    : '/inmobiliaria/subasta',
                children: [
                    {
                        id        : 'inmobiliaria.subasta.administrar',
                        title     : 'Administrar Subasta',
                        type      : 'basic',
                        icon    : 'heroicons_outline:bookmark',
                        link      : '/inmobiliaria/subasta',
                    },
                    {
                        id        : 'inmobiliaria.subasta.verificacion',
                        title     : 'Verificacion Pagos',
                        type      : 'basic',
                        icon    : 'heroicons_outline:wallet',
                        link      : '/inmobiliaria/subasta',
                    },
                ],
            },
            {
                id      : 'inmobiliaria.infocorp',
                title   : 'Exportar datos a Infocorp',
                type : 'basic',
                icon : 'heroicons_outline:arrow-up-tray',
                link : '/inmobiliaria/infocorp',
            },
        ],
    },
    {
        id   : 'tesoreria',
        title: 'Tesoreria',
        subtitle: 'Modulo de Tesoreria',
        type    : 'group',
        icon : 'heroicons_outline:banknotes', //mat_outline:money
        children: [
            {
                id   : 'tesoreria.ingresos',
                title: 'Ingresos',
                type : 'basic',
                icon : 'heroicons_outline:academic-cap',
                link : '/tesoreria/ingresos',
            },
            {
                id   : 'tesoreria.motivos',
                title: 'Motivos',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/tesoreria/motivos',
            },
            {
                id   : 'tesoreria.bancos',
                title: 'Bancos',
                type : 'basic',
                icon : 'heroicons_outline:user-group',
                link : '/tesoreria/bancos',
            },
            {
                id      : 'tesoreria.impoexpo',
                title   : 'IMPORTAR EXPORTAR',
                type    : 'collapsable',
                icon    : 'heroicons_outline:shopping-cart',
                children: [
                    {
                        id   : 'tesoreria.impbanco',
                        title: 'Importar datos del Banco',
                        type : 'basic',
                        link : '/tesoreria/impbanco',
                    },
                    {
                        id   : 'tesoreria.expbanco',
                        title: 'Exportar datos al Banco',
                        type : 'basic',
                        link : '/tesoreria/expbanco',
                    },
                    {
                        id   : 'tesoreria.impoexpo.expconta',
                        title: 'Exportar a Contabilidad',
                        type : 'basic',
                        link : '/apps/impoexpo/expconta',
                    },
                    {
                        id   : 'tesoreria.impoexpo.reptelecredito',
                        title: 'Reporte Telecredito',
                        type : 'basic',
                        link : '/tesoreria/impoexpo/reptelecredito',
                    },
                ],
            },
            {
                id      : 'tesoreria.ingresos',
                title   : 'INGRESOS MENSUALES',
                type    : 'collapsable',
                icon    : 'heroicons_outline:information-circle',
                link    : '/tesoreria/ingresos',
                children: [
                    {
                        id        : 'tesoreria.ingresos.arrendamiento',
                        title     : 'Arrendamiento y Otros',
                        type      : 'basic',
                        link      : '/tesoreria/ingresos/arrendamiento',
                        exactMatch: true,
                    },
                    {
                        id        : 'tesoreria.ingresos.devconigv',
                        title     : 'Devengados con IGV',
                        type      : 'basic',
                        link      : '/tesoreria/ingresos/devconigv',
                        exactMatch: true,
                    },
                    {
                        id        : 'tesoreria.ingresos.devsinigv',
                        title     : 'Devengados sin IGV',
                        type      : 'basic',
                        link      : '/tesoreria/ingresos/devsinigv',
                        exactMatch: true,
                    },
                ],
            },
        ],
    },
    {
        id   : 'legal',
        title: 'Legal',
        subtitle: 'Modulo de Legal',
        type    : 'group',
        icon : 'mat_outline:file_download_done',
        children: [
            {
                id   : 'legal.proclegal',
                title: 'Procesos Legales',
                type : 'basic',
                icon : 'heroicons_outline:academic-cap',
                link : '/tesoreria/proclegal',
            },
            {
                id   : 'legal.opilegal',
                title: 'Opiniones Legales',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/tesoreria/opilegal',
            },
        ],
    },
    {
        id   : 'gerencia',
        title: 'Gerencia General',
        subtitle: 'Modulo de Gerencia General',
        type    : 'group',
        icon : 'mat_outline:admin_panel_settings',
        children: [
            {
                id   : 'gerencia.itlaprobar',
                title: 'ITL por aprobar',
                type : 'basic',
                icon : 'heroicons_outline:academic-cap',
                link : '/gerencia/proclegal',
            },
            {
                id   : 'gerencia.otlobservados',
                title: 'ITL observados',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/gerencia/opilegal',
            },
            {
                id   : 'gerencia.aprobargarantias',
                title: 'Aprobar garantias',
                type : 'basic',
                icon : 'heroicons_outline:academic-cap',
                link : '/gerencia/aprobargarantias',
            },
            {
                id   : 'gerencia.repsgsi',
                title: 'Reporte SGSI',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/gerencia/repsgsi',
            },
        ],
    },
    {
        id   : 'reportes',
        title: 'Reportes',
        subtitle: 'Modulo de Reportes',
        type    : 'group',
        icon : 'heroicons_outline:chart-pie',
        children: [
            {
                id   : 'reportes.itlaprobar',
                title: '01 Margesi Inmobiliario Municipal',
                type : 'basic',
                icon : 'heroicons_outline:academic-cap',
                link : '/reportes/proclegal',
            },
            {
                id   : 'reportes.otlobservados',
                title: '02 Listado de Suministros',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/opilegal',
            },
            {
                id   : 'reportes.aprobargarantias',
                title: '03 Reporte Registro de Ventas Mensual',
                type : 'basic',
                icon : 'heroicons_outline:academic-cap',
                link : '/reportes/aprobargarantias',
            },
            {
                id   : 'reportes.repsgsi',
                title: '04 	Reporte de próximos vencimientos de contrato',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '05 Reporte de contratos vencidos',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '06 Reporte de inspecciones realizadas',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '07 Reporte de ingresos por renta detallado',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '08 Reporte de deuda de renta',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '09 Reporte de ITLs anulados',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '10 Reporte Estadistico de deuda acumulada',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '11 Reporte de Contratos Vigentes',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '12 Reporte de Procesos judiciales Vigentes',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '13 Reporte de Inmuebles con posibilidad a Subastarse',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '14 Reporte de Adquirientes de Bases y Postores Inscritos',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '15 Reporte de Inmuebles con fecha de valorizacion mayor a 2 años',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '16 Reporte Inmuebles Inspecciones Técnica Mayores a 10 Meses',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
            {
                id   : 'reportes.repsgsi',
                title: '17 Reporte Margesi por Año',
                type : 'basic',
                icon : 'heroicons_outline:chat-bubble-bottom-center-text',
                link : '/reportes/repsgsi',
            },
        ],
    },
];
export const compactNavigation: FuseNavigationItem[] = [
    {
        id   : 'inmobiliaria',
        title: 'Inmobiliaria',
        tooltip : 'Inmobiliaria',
        type    : 'aside',
        icon    : 'heroicons_outline:home',
        children: [],
    },
    {
        id   : 'tesoreria',
        title: 'Tesoreria',
        tooltip : 'Inmobiliaria',
        type    : 'aside',
        icon    : 'mat_outline:money',
        children: [],
    },
    {
        id   : 'legalaa',
        title: 'Legal',
        tooltip : 'Legal',
        type    : 'aside',
        icon : 'mat_outline:file_download_done',
        children: [],
    },
    {
        id   : 'gerencia',
        title: 'Gerencia General',
        tooltip : 'Gerencia General',
        type    : 'aside',
        icon : 'mat_outline:admin_panel_settings',
        children: [],
    },
    {
        id   : 'reportes',
        title: 'Reportes',
        tooltip : 'Reportes',
        type    : 'aside',
        icon : 'heroicons_outline:chart-pie',
        children: [],
    },
];
export const futuristicNavigation: FuseNavigationItem[] = [
    {
        id   : 'inmobiliaria',
        title: 'Inmobiliaria',
        type    : 'group',
        children: [], 
    },
    {
        id   : 'tesoreria',
        title: 'Tesoreria',
        type    : 'group',
        children: [], 
    },
    {
        id   : 'legal',
        title: 'Legal aa',
        type    : 'group',
        children: [], 
    },
    {
        id   : 'gerencia',
        title: 'Gerencia General',
        type    : 'group',
        children: [], 
    },
    {
        id   : 'reportes',
        title: 'Reportes',
        type    : 'group',
        children: [], 
    },
];
export const horizontalNavigation: FuseNavigationItem[] = [
    {
        id   : 'inmobiliaria',
        title: 'Inmobiliaria',
        type    : 'group',
        icon    : 'heroicons_outline:home',
        children: [],
    },
    {
        id   : 'tesoreria',
        title: 'Tesoreria',
        type    : 'group',
        icon    : 'heroicons_outline:banknotes',
        children: [],
    },
    {
        id   : 'legal',
        title: 'Legal  sss',
        type    : 'group',
        icon    : 'mat_outline:file_download_done',
        children: [],
    },
    {
        id   : 'gerencia',
        title: 'Gerencia General',
        type : 'group',
        icon : 'mat_outline:admin_panel_settings',
        children: [],
    },
    {
        id   : 'reportes',
        title: 'Reportes',
        type : 'group',
        icon : 'heroicons_outline:chart-pie',
        children: [],
    },
];
